### ISSUE TITLE
Update spatie/phpunit-snapshot-assertions dependency

### ISSUE THREAD

**Issue by Luc45** [lucatume/wp-snapshot-assertions#5]
I'd like to request to update the dependency `spatie/phpunit-snapshot-assertions`.

It's currently locked at ^1.12 (`>=1.12  < 2.0`), which locks phpunit version to 5, 6 and 7. I use PHPUnit 8, therefore I can't use this package.

`spatie/phpunit-snapshot-assertions` is already on version ^4, which locks the PHPUnit versions to `^8.3|^9.0`.

`wp-snapshot-assertions` could either lock the version to a more recent one, or support multiple major versions of `spatie/phpunit-snapshot-assertions` that cover more PHPUnit versions.

Thank you.

**Comment by lucatume** [comment]
Closed in #7
